--1
CREATE TABLE Student (studentID INTEGER, titleID INTEGER NOT NULL, foreName CHAR(80), familyName CHAR(80), dateOfBirth DATE NOT NULL, CONSTRAINT StudentsKey PRIMARY KEY (studentID), CONSTRAINT TitleIDKey FOREIGN KEY (titleID) REFERENCES Titles (titleID) ON DELETE CASCADE ON UPDATE CASCADE);

--2
CREATE TABLE Lecturer (lecturerID INTEGER, titleID INTEGER NOT NULL, foreName CHAR(80), familyName CHAR(80), CONSTRAINT LecturerKey PRIMARY KEY (lecturerID), CONSTRAINT TitleIDKey FOREIGN KEY (titleID) REFERENCES Titles (titleID) ON DELETE CASCADE ON UPDATE CASCADE);

--3
CREATE TABLE StudentRegistration (studentID INTEGER UNIQUE NOT NULL, yearOfStudy INTEGER NOT NULL, registrationTypeID INTEGER NOT NULL, CONSTRAINT StudentRegistrationKey FOREIGN KEY (studentID) REFERENCES Student (studentID) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT StudentRegistrationTypeKey FOREIGN KEY (registrationTypeID) REFERENCES RegistrationType(registrationTypeID) ON DELETE CASCADE ON UPDATE CASCADE);

--4
CREATE TABLE StudentContact (studentID INTEGER UNIQUE NOT NULL, eMailAddress CHAR(80), postalAddress CHAR(80) NOT NULL, CONSTRAINT StudentContactKey FOREIGN KEY (studentID) REFERENCES Student (studentID) ON DELETE CASCADE ON UPDATE CASCADE);

--5
CREATE TABLE NextOfKinContact (studentID INTEGER UNIQUE NOT NULL, name CHAR(80) NOT NULL, eMailAddress CHAR(80), postalAddress CHAR(80) NOT NULL, CONSTRAINT NextOfKinContactKey FOREIGN KEY (studentID) REFERENCES Student (studentID) ON DELETE CASCADE ON UPDATE CASCADE);

--6
CREATE TABLE LecturerContact (lecturerID INTEGER UNIQUE NOT NULL, Office CHAR(80) NOT NULL, eMailAddress CHAR(80), CONSTRAINT LecturerContactKey FOREIGN KEY (lecturerID) REFERENCES Lecturer (lecturerID) ON DELETE CASCADE ON UPDATE CASCADE);

--7
CREATE TABLE Tutor (studentID INTEGER UNIQUE NOT NULL, lecturerID INTEGER NOT NULL, CONSTRAINT TutorStudentKey FOREIGN KEY (studentID) REFERENCES Student (studentID) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT TutorLecturerKey FOREIGN KEY (lecturerID) REFERENCES Lecturer (lecturerID) ON DELETE CASCADE ON UPDATE CASCADE);

--8
CREATE TABLE Titles (titleID INTEGER, titleString CHAR(80) NOT NULL, CONSTRAINT TitlesKey PRIMARY KEY (titleID))

--9
CREATE TABLE RegistrationType (registrationTypeID INTEGER, description CHAR(80), CONSTRAINT RegistrationTypeKey PRIMARY KEY (registrationTypeID));
